TdrTiSystems/Controllers/CartaPorteController.cs
using Microsoft.AspNetCore.Mvc;
using CapaEntidad;
using CapaNegocio;
using TdrTiSystems.Filter;

namespace TdrTiSystems.Controllers
{
    
    public class CartaPorteController : Controller
    {
        [ServiceFilter(typeof(Seguridad))]
        public IActionResult Index()
        {
            return View();
        }
        public List<CartaPorteCLS> listarCartaPorte()
        {
            CartaPorteBL obj = new CartaPorteBL();
            return obj.listarCartaPorte();
        }
        public List<CartaPorteCLS> filtrarCartaPorte(string segmento)
        {
            CartaPorteBL obj = new CartaPorteBL();
            return obj.filtrarCartaPorte(segmento);
        }
    }
}

TdrTiSystems/Controllers/LoginController.cs
using CapaEntidad;
using CapaNegocio;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Microsoft.AspNetCore.Http;

namespace TdrTiSystems.Controllers
{
    public class LoginController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public List<PaginaCLS> listarMenu(int iidtipousuario)
        {
            PaginaBL oPaginaBL = new PaginaBL();
            return oPaginaBL.listarMenu(iidtipousuario);
        }
        public IActionResult Cerrarsesion()
        {
            HttpContext.Session.Clear();
            HttpContext.Session.Remove("persona");
            return RedirectToAction("Index");
        }
        public PersonaCLS login(string usuario, string contra)
        {
            PersonaBL oPersonaBL = new PersonaBL();
            PersonaCLS oPersonaCLS= oPersonaBL.login(usuario, contra);
            if (oPersonaCLS.iidusuario != 0)
            {
                string objCadena = JsonConvert.SerializeObject(oPersonaCLS);
                HttpContext.Session.SetString("persona", objCadena);
                int iidtipousuario = oPersonaCLS.iidtipousuario;
                List<PaginaCLS> listapagina = listarMenu(iidtipousuario);
                string objLista = JsonConvert.SerializeObject(listapagina);
                HttpContext.Session.SetString("menu", objLista);
            }
            else
            {
                HttpContext.Session.Remove("persona");
            }
            return oPersonaCLS;
        }
    }
}

TdrTiSystems/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http;
@using Newtonsoft.Json;
@using CapaEntidad;
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    
    <title>TDR | TI APPS</title>
    <link rel="icon" href="~/img/icon.png">
    <link rel="stylesheet" href="~/css/bootstrap.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="https://kit.fontawesome.com/789a3ce2b4.js" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.slim.js"
            integrity="sha256-HwWONEZrpuoh951cQD1ov2HUK5zA5DwJ1DNUXaM6FsY="
            crossorigin="anonymous"></script>
             <script>
            //Script que impide el uso del botón atrás del navegador
            window.location.hash = "no-back-button";
            window.location.hash = "Again-No-back-button";
            window.onhashchange = function () { window.location.hash = ""; }
        </script>
       
    <style>
        
/* width */
::-webkit-scrollbar {
  width: 10px;
}

/* Track */
::-webkit-scrollbar-track {
  box-shadow: inset 0 0 5px grey; 
  border-radius: 10px;
}
 
/* Handle */
::-webkit-scrollbar-thumb {
 background: grey;
  border-radius: 10px;
}

/* Handle on hover */
::-webkit-scrollbar-thumb:hover {
  background-image: linear-gradient(to bottom right, #00315f,#f7be31 );
}

        body {
            margin: 0;
            background: #062746;
            font-family: Arial;
        }

        nav {
            position: fixed;
            width: 100%;
            max-width: 300px;
            bottom: 0;
            top: 0;
            display: block;
            min-height: 300px;
            height: 100%;
            color: #fff;
            opacity: 0.8;
            transition: all 300ms;
            -moz-transition: all 300ms;
            -webkit-transition: all 300ms;
        }

            nav .vertical-menu hr {
                opacity: 0.1;
                border-width: 0.5px;
            }

            nav ul {
                width: 90%;
                padding-inline-start: 0;
                margin: 10px;
                height: calc(100% - 20px);
            }

            nav .vertical-menu-logo {
                padding: 10px;
                font-size: 1.3em;
                position: relative
            }

                nav .vertical-menu-logo .open-menu-btn {
                    width: 30px;
                    height: max-content;
                    position: absolute;
                    display: block;
                    right: 20px;
                    top: 0;
                    bottom: 0;
                    margin: auto;
                    cursor: pointer;
                }

                    nav .vertical-menu-logo .open-menu-btn hr {
                        margin: 5px 0
                    }

            nav li {
                list-style: none;
                padding: 10px 10px;
                cursor: pointer;
            }

                /*nav li:hover {
                    -webkit-transition-delay:0s;
                   -webkit-transition-duration:0.5s;
                   -webkit-transition-property:all;
                   -webkit-transition-timing-function:ease;
                   background-color:#95a5a6;
                   border-start-end-radius:10px !important;
                }*/

                .stiloli:hover {
                     -webkit-transition-delay:0s;
                   -webkit-transition-duration:0.5s;
                   -webkit-transition-property:all;
                   -webkit-transition-timing-function:ease;
                   background-color:#95a5a6;
                   border-start-end-radius:10px !important;
                }
                .stilolic:hover {
                    -webkit-transition-delay:0s;
                   -webkit-transition-duration:0.5s;
                   -webkit-transition-property:all;
                   -webkit-transition-timing-function:ease;
                     transform: scale(1.5);
                }

                nav li#user-info {
                    position: absolute;
                    bottom: 0;
                    width: 80%;
                }

                    nav li#user-info > span {
                        display: block;
                        float: right;
                        font-size: 0.9em;
                        position: relative;
                        opacity: 0.6;
                    }

                        nav li#user-info > span:after {
                            content: '';
                            width: 12px;
                            height: 12px;
                            display: block;
                            position: absolute;
                            background: #13ff13;
                            left: -20px;
                            top: 0;
                            bottom: 0;
                            margin: auto;
                            border-radius: 50%;
                        }

        .content-wrapper {
            width: calc(100% - 300px);
            height: 100%;
            position: fixed;
            background: #fff;
            left: 300px;
            padding: 20px;
            z-index: 1500;
        }

        .closed-menu .content-wrapper {
            width: 100%;
            left: 50px;
        }

        .content-wrapper {
            transition: all 300ms;
        }

        .vertical-menu-wrapper .vertical-menu-logo div {
            transition: all 100ms;
        }

        .closed-menu .vertical-menu-wrapper .vertical-menu-logo div {
            margin-left: -100px;
        }

        .vertical-menu-wrapper .vertical-menu-logo .open-menu-btn {
            transition: all 300ms;
        }

        .closed-menu .vertical-menu-wrapper .vertical-menu-logo .open-menu-btn {
            left: 7px;
            right: 100%;
        }

        .closed-menu .vertical-menu-wrapper ul, .closed-menu .vertical-menu-wrapper hr {
            margin-left: -300px;
        }

        .vertical-menu-wrapper ul, .vertical-menu-wrapper hr {
            transition: all 100ms;
        }

        .content-wrapper {
            background: #ebebeb;
        }

        .content {
            width: 100%;
            min-height: 90%;
            background: #fff;
            border-radius: 10px;
            padding: 30px;
        }
            
        
    </style>
    <script>
        $(document).ready(function () {
            $('.open-menu-btn').on('click', function () {
                if ($('body').hasClass('closed-menu')) {
                    $('body').removeClass('closed-menu');
                } else $('body').addClass('closed-menu');
            });
        });
    </script>
</head>
<body>
    @{
        string cadena = Context.Session.GetString("persona");
        PersonaCLS oPersonaCLS = JsonConvert.DeserializeObject<PersonaCLS>(cadena);
        string cadenaMenu = Context.Session.GetString("menu");
       List<PaginaCLS> listapagina =  JsonConvert.DeserializeObject<List<PaginaCLS>>(cadenaMenu);
    }
    
    <nav class="vertical-menu-wrapper overflow-auto">
        <div class="vertical-menu-logo">
            <ul class="vertical-menu">
             <li>

                <img class="img-fluid" src="~/img/logo.png" />
                

            </li></ul>
            <span class="open-menu-btn"><hr><hr><hr></span>
        </div>
        <ul class="vertical-menu">
             <li>

                <b class="nav-link text-light" style="font-size:25px !important; text-align:center !important">¡Bienvenido!</b>
                

            </li>
            <li>

                <b class="nav-link text-light" style="font-size:14px !important;text-align:center !important"><i class="fas fa-user-alt stilolic" style="color: #58db58 !important;font-size:30px"></i></b>
                
            </li>
            <li>

                <b class="nav-link text-light" style="font-size:15px !important;text-align:center !important">@oPersonaCLS.nombrecompleto</b>
                <hr />
            </li>
            @foreach(PaginaCLS oPaginaCLS in listapagina)
            {
                 <li class="stiloli">
                    <a class="nav-link text-light" asp-area="" asp-controller="@oPaginaCLS.controlador" asp-action="@oPaginaCLS.accion">
                        <i class="fa fa-check-circle" style="color:#f7be31"></i> @oPaginaCLS.mensaje
                    </a>
                </li>
            }
            
            <li>
                <hr />
                <a class="nav-link text-light stiloli" asp-area="" asp-controller="Login" asp-action="Cerrarsesion">
                    <i class="fa fa-sign-out" style="color:red"></i> <b>Cerrar sesión</b>
                </a>
                  <hr />
            </li>

            <li style="text-light;text-align:center !important;"><small>2019 Copyright <br /> &copy; TDR Soluciones Logísticas</small></li>
        </ul>

    </nav>
    <div class="content-wrapper" style="overflow:scroll">
        <div class="content shadow-lg">
            @RenderBody()
        </div>
    </div>
    @*<header>
            <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
                <div class="container">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TDR |</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                        <ul class="navbar-nav flex-grow-1">

                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area=""
                                   asp-controller="CartaPorte" asp-action="Index">
                                    CartaPorte
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
        </header>
        <input type="hidden" id="hdfOculto" value="@Url.Content("~")" />
        <div class="container">
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>*@
    <input type="hidden" id="hdfOculto" value="@Url.Content("~")" />

    <div id="divLoading" style="display:none;background-image:url(../img/loading.gif);position:absolute;top:0;left:0;width:100%;height:100%;background-repeat:no-repeat;background-position:center;z-index:2000"></div>


    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://kit.fontawesome.com/789a3ce2b4.js" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>